<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class CABSB_AI_Builder {

    public static function init() {
        add_action( 'admin_menu', array( __CLASS__, 'menu' ) );
        add_action( 'admin_init', array( __CLASS__, 'handle_generate' ) );
    }

    public static function menu() {
        add_submenu_page(
            'cab-site-builder',
            __( 'AI Builder', 'cab-site-builder' ),
            __( 'AI Builder', 'cab-site-builder' ),
            'manage_options',
            'cabsb-ai-builder',
            array( __CLASS__, 'page' )
        );
    }

    public static function page() {
        ?>
        <div class="wrap">
            <h1><?php esc_html_e( 'AI Layout Builder', 'cab-site-builder' ); ?></h1>
            <p><?php esc_html_e( 'Generate ready-to-edit landing sections as CAB Elements. Connect your own AI endpoint later, or use the built-in local generator now.', 'cab-site-builder' ); ?></p>
            <form method="post">
                <?php wp_nonce_field( 'cabsb_ai_builder', 'cabsb_ai_nonce' ); ?>
                <table class="form-table" role="presentation">
                    <tr>
                        <th><label for="cabsb_ai_prompt">Prompt</label></th>
                        <td><input id="cabsb_ai_prompt" name="cabsb_ai_prompt" class="regular-text" placeholder="Example: SEO agency landing hero"></td>
                    </tr>
                    <tr>
                        <th><label for="cabsb_ai_type">Section Type</label></th>
                        <td>
                            <select id="cabsb_ai_type" name="cabsb_ai_type">
                                <option value="hero">Hero</option>
                                <option value="features">Features</option>
                                <option value="cta">CTA</option>
                                <option value="pricing">Pricing</option>
                            </select>
                        </td>
                    </tr>
                </table>
                <?php submit_button( __( 'Generate CAB Element', 'cab-site-builder' ), 'primary', 'cabsb_generate_ai_element' ); ?>
            </form>
        </div>
        <?php
    }

    public static function handle_generate() {
        if ( empty( $_POST['cabsb_generate_ai_element'] ) ) {
            return;
        }

        if ( ! current_user_can( 'manage_options' ) || empty( $_POST['cabsb_ai_nonce'] ) || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['cabsb_ai_nonce'] ) ), 'cabsb_ai_builder' ) ) {
            return;
        }

        $prompt = isset( $_POST['cabsb_ai_prompt'] ) ? sanitize_text_field( wp_unslash( $_POST['cabsb_ai_prompt'] ) ) : 'Modern landing section';
        $type   = isset( $_POST['cabsb_ai_type'] ) ? sanitize_key( wp_unslash( $_POST['cabsb_ai_type'] ) ) : 'hero';
        $html   = self::local_template( $prompt, $type );

        $post_id = wp_insert_post( array(
            'post_type'    => 'cabsb_element',
            'post_title'   => 'AI ' . ucfirst( $type ) . ' - ' . $prompt,
            'post_content' => $html,
            'post_status'  => 'draft',
        ) );

        if ( $post_id ) {
            update_post_meta( $post_id, '_cabsb_location', 'before_content' );
            update_post_meta( $post_id, '_cabsb_display', 'homepage' );
        }
    }

    private static function local_template( $prompt, $type ) {
        $title = esc_html( ucwords( $prompt ) );

        if ( 'features' === $type ) {
            return '[cabsb_container][cabsb_grid columns="3"]<div><h3>Fast</h3><p>Lightweight structure for better performance.</p></div><div><h3>Flexible</h3><p>Reusable sections and visual controls.</p></div><div><h3>Profitable</h3><p>Marketing-ready layouts for conversion.</p></div>[/cabsb_grid][/cabsb_container]';
        }

        if ( 'cta' === $type ) {
            return '[cabsb_hero title="' . $title . '" subtitle="Turn visitors into subscribers, leads, and customers."][cabsb_button text="Start Now" url="#"][/cabsb_hero]';
        }

        if ( 'pricing' === $type ) {
            return '[cabsb_container][cabsb_grid columns="3"]<div><h3>Starter</h3><p>$9/mo</p></div><div><h3>Growth</h3><p>$29/mo</p></div><div><h3>Pro</h3><p>$79/mo</p></div>[/cabsb_grid][/cabsb_container]';
        }

        return '[cabsb_hero title="' . $title . '" subtitle="A modern section generated by CAB AI Builder."][cabsb_button text="Learn More" url="#"][/cabsb_hero]';
    }
}
